music_directory    "~/Music"
playlist_directory "~/.local/lib/mpd/playlists"
db_file            "~/.local/lib/mpd/mpd.db"
log_file           "~/.local/lib/mpd/mpd.log"
pid_file           "~/.local/lib/mpd/mpd.pid"
state_file         "~/.local/lib/mpd/mpdstate"

# Listen on a local port not requiring root
bind_to_address    "127.0.0.1"
port               "6600"
