# ~/dotfiles/hypr/hyprlock.conf

general {
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    color = rgba(5, 10, 15, 0.95)    # Deep cyber-space black/blue
    blur_passes = 2 # Number of times to apply the blur effect
    blur_size = 7 # Size of the blur effect
}





# TIME DISPLAY (Hacker Style Clock)
label {
    monitor =
    text = $TIME  # Displays current time in HH:MM:SS format
    color = rgba(0, 255, 120, 0.85)  # Matrix Terminal Green
    font_size = 100
    font_family = JetBrainsMono Nerd Font
    position = 0, 80                # Pushed up slightly
    halign = center
    valign = center
}

# OPTION A: CUSTOM TEXT (Hacker Warning String)
label {
    monitor =
    text = LOCKED!!
    color = rgba(255, 50, 50, 0.8)   # Alert Red text
    font_size = 90
    # bold and futuristic font, you can use fonts like "Orbitron", "Audiowide", or "Exo 2" for a cyberpunk feel
    font_family = Exo 2
    position = 0, 200                 # Positioned above input box
    halign = center
    valign = center
}

# OPTION B: PICTURE LOGO (Uncomment by removing the '#' if you want an image!)
# image {
#     monitor =
#     path = /home/skymoon@baby/Pictures/screenshots/pro.png # Change to your actual image path
#     size = 120 # Size of the image
#     border_size = 2
#     border_color = rgba(0, 255, 120, 1) # Green border around image
#     position = 0, -90
#     halign = center
#     valign = center
# }

# INPUT FIELD
input-field {
    monitor =
    size = 260, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.40
    dots_center = true
    outer_color = rgba(0, 255, 120, 1)        # Cyber green border
    inner_color = rgba(10, 20, 25, 0.8)        # Dark inner field
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false

    # FIXED: Changed ##00ff78 to #00ff78
    #placeholder_text = <span foreground="#00ff78">root@machine:~ </span>

    hide_input = false
    position = 0, -20
    halign = center
    valign = center
    border_radius = 10
}

# my quote at the bottom of the screen
label {
    monitor =
    text = Remember the Goal and Keep it Fresh
    color = rgba(16, 59, 126, 0.85)
    font_size = 16
    #font family of handwriting style like(caveaet, pacifico,  dancing script, etc.)
    font_family = Caveat
    position = 0, -80
    halign = center
    valign = center

}

