# ~/dotfiles/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoids launching multiple instances
    before_sleep_cmd = loginctl lock-session    # Ensures system locks safely before suspension
    after_sleep_cmd = hyprctl dispatch dpms on  # Turns display back on after waking up

    #force idle even with video playing (e.g. YouTube, Netflix, etc.)
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

# 1. DIM SCREEN: After 4 minutes (240s) of inactivity
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 10%  # Dim display to 10%
    on-resume = brightnessctl -s set 100%  # Instantly restore brightness on user movement
}

# 2. LOCK SCREEN: After 5 minutes (300s) of inactivity
listener {
    timeout = 300
    on-timeout = loginctl lock-session     # Triggers hyprlock through systemd session
}

# 3. SUSPEND/SLEEP: After 10 minutes (600s) of inactivity
listener {
    timeout = 600
    on-timeout = systemctl suspend         # Automatically puts machine to deep sleep
}
