[ids]
*

[main]
# right alt acts as super key
rightalt = leftmeta

#caps lock as escape when tapped, ctr when held
capslock = overload(control, esc)

#esc as capslock
esc = capslock

#arrows from  the home row
leftcontrol+h = left
leftcontrol+j = down
leftcontrol+k = up
leftcontrol+l = right
